// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsN-a6PkkwhHSlQeGejd_iSneaK-jDXgY',
    appId: '1:763787379590:web:48703ff1dc30d86b07a207',
    messagingSenderId: '763787379590',
    projectId: 'amplify-2ecfc',
    authDomain: 'amplify-2ecfc.firebaseapp.com',
    storageBucket: 'amplify-2ecfc.firebasestorage.app',
    measurementId: 'G-LR3W9MRBVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4lAwjZBy44Nksf6mZk8lOh8B4NBEu3oM',
    appId: '1:763787379590:android:4db7d22b0340ab2d07a207',
    messagingSenderId: '763787379590',
    projectId: 'amplify-2ecfc',
    storageBucket: 'amplify-2ecfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABnv40ELfuQ7zMA48HyIUazWdRQoF_aJs',
    appId: '1:763787379590:ios:354f049d9fb796b307a207',
    messagingSenderId: '763787379590',
    projectId: 'amplify-2ecfc',
    storageBucket: 'amplify-2ecfc.firebasestorage.app',
    iosBundleId: 'com.example.amplify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABnv40ELfuQ7zMA48HyIUazWdRQoF_aJs',
    appId: '1:763787379590:ios:354f049d9fb796b307a207',
    messagingSenderId: '763787379590',
    projectId: 'amplify-2ecfc',
    storageBucket: 'amplify-2ecfc.firebasestorage.app',
    iosBundleId: 'com.example.amplify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsN-a6PkkwhHSlQeGejd_iSneaK-jDXgY',
    appId: '1:763787379590:web:02364f428de3aedb07a207',
    messagingSenderId: '763787379590',
    projectId: 'amplify-2ecfc',
    authDomain: 'amplify-2ecfc.firebaseapp.com',
    storageBucket: 'amplify-2ecfc.firebasestorage.app',
    measurementId: 'G-510WXJW1RV',
  );
}
